version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: zilTTlA_289AVPT
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db